# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configservicenow',
            name='host',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
