# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0002_auto_20170322_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configservicenow',
            name='host',
            field=models.CharField(max_length=20),
        ),
    ]
